# Generated by Django 5.0.14 on 2026-06-11 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0001_initial"),
        ("hubs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="situationreport",
            name="hub",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="hubs.hub",
            ),
        ),
    ]
