# Generated by Django 5.0.14 on 2026-06-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReportingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_reporting_enabled', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('include_activity_summary', models.BooleanField(default=True)),
                ('include_hubs_summary', models.BooleanField(default=True)),
                ('include_alerts_summary', models.BooleanField(default=True)),
                ('include_ai_performance', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Reporting Configuration',
                'db_table': 'ai_reporting_config',
            },
        ),
        migrations.CreateModel(
            name='MessageReviewConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_threshold', models.IntegerField(default=70)),
                ('autonomous_classification', models.BooleanField(default=True)),
                ('review_report_frequency', models.CharField(choices=[('60min', '60 Minutes'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='60min', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message Review Configuration',
                'db_table': 'message_review_config',
            },
        ),
    ]
