# Generated by Django 5.0.14 on 2026-06-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aireportingconfig_messagereviewconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situationreport',
            name='hub',
        ),
    ]
