# Generated by Django 5.0.14 on 2026-06-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_remove_situationreport_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireportingconfig',
            name='use_ai_summary',
            field=models.BooleanField(default=False),
        ),
    ]
