# Generated by Django 5.0.14 on 2026-07-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_aireportingconfig_use_ai_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aireportingconfig',
            name='frequency',
        ),
        migrations.AddField(
            model_name='aireportingconfig',
            name='frequency_interval_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
