# Generated by Django 5.0.14 on 2026-08-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_remove_aireportingconfig_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireportingconfig',
            name='include_classification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aireportingconfig',
            name='include_extraction',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aireportingconfig',
            name='include_triage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aireportingconfig',
            name='structured_reporting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='situationreport',
            name='context_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='situationreport',
            name='extraction',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='situationreport',
            name='hazard_classification',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='situationreport',
            name='report_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='situationreport',
            name='report_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='situationreport',
            name='triage',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
