# Generated by Django 5.0.14 on 2026-06-23 15:26

from django.db import migrations


def seed_static_content(apps, schema_editor):
    StaticContent = apps.get_model("content", "StaticContent")
    StaticContent.objects.get_or_create(
        slug="privacy-policy",
        defaults={
            "title": "Privacy Policy",
            "content": "Your privacy policy content goes here.",
        },
    )
    StaticContent.objects.get_or_create(
        slug="terms-and-conditions",
        defaults={
            "title": "Terms and Conditions",
            "content": "Your terms and conditions content goes here.",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_static_content),
    ]
