# Generated by Django 5.0.14 on 2026-06-11 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comms', '0001_initial'),
        ('hazards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundmessage',
            name='classified_hazard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazards.hazard'),
        ),
    ]
