# Generated by Django 5.0.14 on 2026-06-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0003_comms_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='additional_hazard',
            field=models.CharField(blank=True, choices=[('collapsed_building', 'Collapsed Building'), ('landslide', 'Landslide'), ('power_line_down', 'Power Line Down'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='assistance_type',
            field=models.CharField(blank=True, choices=[('medical', 'Medical'), ('trapped', 'Trapped'), ('need_supplies', 'Need Supplies'), ('unsafe', 'Unsafe Area'), ('fire', 'Fire'), ('fallen_tree', 'Fallen Tree'), ('utility_pole', 'Damaged Utility Pole')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='help_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='checkins/'),
        ),
    ]
