# Generated by Django 5.0.14 on 2026-06-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0004_checkin_emergency_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='additional_hazard',
            field=models.CharField(blank=True, choices=[('collapsed_building', 'Collapsed Building'), ('landslide', 'Landslide'), ('power_line_down', 'Power Line Down'), ('other', 'Other'), ('lost_or_separated', 'Lost or Separated'), ('mental_health_crisis', 'Mental Health Crisis'), ('fire', 'Fire')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='assistance_type',
            field=models.CharField(blank=True, choices=[('medical', 'Medical'), ('trapped', 'Trapped'), ('need_supplies', 'Need Supplies'), ('unsafe_building', 'Unsafe Area'), ('fallen_tree', 'Fallen Tree'), ('utility_pole', 'Damaged Utility Pole')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=19, null=True),
        ),
    ]
