# Generated by Django 5.0.14 on 2026-06-29 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0005_alter_checkin_additional_hazard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('escalated', 'Escalated'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='checkin',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkin',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='assistance_type',
            field=models.CharField(blank=True, choices=[('medical', 'Medical'), ('trapped', 'Trapped'), ('need_supplies', 'Need Supplies'), ('unsafe_building', 'Unsafe Area'), ('fallen_tree', 'Fallen Tree'), ('utility_pole', 'Damaged Utility Pole'), ('security_concern', 'Security Concern'), ('vehicle_breakdown', 'Vehicle Breakdown'), ('stranded', 'Stranded')], max_length=30, null=True),
        ),
    ]
