# Generated by Django 5.0.14 on 2026-07-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0006_checkin_review_status_checkin_reviewed_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
