# Generated by Django 5.0.14 on 2026-07-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0007_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='assistance_type',
            field=models.CharField(blank=True, choices=[('medical', 'Medical'), ('trapped', 'Trapped'), ('emergency_medical', 'Emergency Medical'), ('need_supplies', 'Need Supplies'), ('unsafe_building', 'Unsafe Area'), ('fallen_tree', 'Fallen Tree'), ('utility_pole', 'Damaged Utility Pole'), ('security_concern', 'Security Concern'), ('vehicle_breakdown', 'Vehicle Breakdown'), ('stranded', 'Stranded')], max_length=30, null=True),
        ),
    ]
