# Generated by Django 5.0.14 on 2026-06-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0005_hazard_review_status_hazard_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='category',
            field=models.CharField(choices=[('flood', 'Flood'), ('fallen_tree', 'Fallen Tree'), ('blocked_road', 'Blocked Road'), ('utility_pole', 'Damaged Utility Pole'), ('medical', 'Urgent Medical'), ('fire', 'Fire'), ('collapsed_building', 'Collapsed Building'), ('power_line_down', 'Power Line Down'), ('landslide', 'Landslide'), ('earthquake', 'Earthquake'), ('storm', 'Storm'), ('other', 'Other')], max_length=30),
        ),
    ]
