# Generated by Django 5.0.14 on 2026-06-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0006_alter_hazard_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
