# Generated by Django 5.0.14 on 2026-07-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0007_latlng_to_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='category',
            field=models.CharField(choices=[('flooding', 'Flood'), ('fallen_tree', 'Fallen Tree'), ('blocked_road', 'Blocked Road'), ('fallen_utility_pole', 'Fallen Utility Pole'), ('medical', 'Urgent Medical'), ('fire', 'Fire'), ('collapsed_building', 'Collapsed Building'), ('power_line_down', 'Power Line Down'), ('landslide', 'Landslide'), ('earthquake', 'Earthquake'), ('storm', 'Storm'), ('other', 'Other')], max_length=30),
        ),
    ]
