# Generated by Django 5.0.14 on 2026-06-11 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hubs.hub'),
        ),
    ]
