# Generated by Django 5.0.14 on 2026-06-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_checkin_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='people_count',
            new_name='device_count',
        ),
    ]
