server {
    listen 80;
    server_name content.sparkcentra.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name content.sparkcentra.com;
    resolver 127.0.0.11 ipv6=off valid=10s;

    ssl_certificate /etc/letsencrypt/live/content.sparkcentra.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/content.sparkcentra.com/privkey.pem;

    add_header Strict-Transport-Security "max-age=63072000" always;
    add_header X-Content-Type-Options "nosniff" always;

    location / {
        set $content_backend "http://spark_content";
        proxy_pass $content_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }
}