server {
    listen 80;
    server_name gov.sparkcentra.com;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name gov.sparkcentra.com;
    ssl_certificate /etc/letsencrypt/live/admin.sparkcentra.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/admin.sparkcentra.com/privkey.pem;

    location /api/ {
        set $backend "http://django:8000";
        proxy_pass $backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }

    location / {
        set $backend "http://gov:80";
        proxy_pass $backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }
}
