# Generated by Django 5.0.14 on 2026-06-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('low_battery', 'Low Battery'), ('critical', 'Critical')], default='open', max_length=20)),
                ('battery_percentage', models.PositiveIntegerField(default=100)),
                ('solar_input_w', models.IntegerField(blank=True, null=True)),
                ('solar_output_w', models.IntegerField(blank=True, null=True)),
                ('estimated_runtime_h', models.FloatField(blank=True, null=True)),
                ('starlink_status', models.BooleanField(default=True)),
                ('max_concurrent_bookings', models.PositiveIntegerField(default=5)),
                ('community_secret_code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'hubs',
            },
        ),
    ]
