# Generated by Django 5.0.14 on 2026-06-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hubs", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hub",
            name="community_secret_code",
        ),
    ]
