# Generated by Django 5.0.14 on 2026-07-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0003_remove_hub_community_secret_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='total_ports',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
